name: capitao_maybank
description: CAPITAO_MAYBANK - assistente pessoal com Gemini
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.0
  flutter_tts: ^4.0.0
  speech_to_text: ^7.0.0
  url_launcher: ^6.2.0

flutter:
  uses-material-design: true
